# Generated by Django 3.0 on 2021-07-21 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210721_1749'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='user_management',
        ),
    ]
